// data.js
const blogsData = [
  {
    id: 1,
    title: "Co operative Movement",
    date: "12 Jan, 2022",
    // category: "Fashion",
    image: "images/portfolio-item11.jpg",
    content: "Dictum elit tortor, vel pretium, quis. Consequat suspendisse...",
  },
  {
    id: 2,
    title: "Contributions to Sandalankawa",
    date: "18 Jan, 2022",
    // category: "Fashion",
    image: "images/portfolio-item17.jpg",
    content: "vel pretium suspendisse ultrices...",
  },
  {
    id: 3,
    title: "National Development",
    date: "12 Jan, 2022",
    // category: "Fashion",
    image: "images/portfolio-item11.jpg",
    content: "Dictum elit tortor, vel pretium, quis. Consequat suspendisse...",
  },
  {
    id: 4,
    title: "Other",
    date: "18 Jan, 2022",
    category: "",
    image: "images/portfolio-item17.jpg",
    content: "vel pretium suspendisse ultrices...",
  },
  // {
  //   id: 5,
  //   title: "How to look outstanding in pastel",
  //   date: "12 Jan, 2022",
  //   category: "Fashion",
  //   image: "images/portfolio-item11.jpg",
  //   content: "Dictum elit tortor, vel pretium, quis. Consequat suspendisse...",
  // },
  // {
  //   id: 6,
  //   title: "Top 10 fashion trend for summer",
  //   date: "18 Jan, 2022",
  //   category: "Fashion",
  //   image: "images/portfolio-item17.jpg",
  //   content: "vel pretium suspendisse ultrices...",
  // },
  // {
  //   id: 7,
  //   title: "How to look outstanding in pastel",
  //   date: "12 Jan, 2022",
  //   category: "Fashion",
  //   image: "images/portfolio-item11.jpg",
  //   content: "Dictum elit tortor, vel pretium, quis. Consequat suspendisse...",
  // },
  // {
  //   id: 8,
  //   title: "Top 10 fashion trend for summer",
  //   date: "18 Jan, 2022",
  //   category: "Fashion",
  //   image: "images/portfolio-item17.jpg",
  //   content: "vel pretium suspendisse ultrices...",
  // },
  // Add more blog entries here
];
