const imagesData = [
  // {
  //   id: 1,
  //   category: ["All", "urban"],
  //   imageUrl: "images/portfolio-thumb-1.jpg",
  //   thumbUrl: "images/portfolio-thumb-1.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 1.",
  // },
  // {
  //   id: 2,
  //   category: ["All", "family", "events"],
  //   imageUrl: "images/portfolio-item2.jpg",
  //   thumbUrl: "images/portfolio-thumb-2.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 2.",
  // },
  // // Add more items as needed...
  // {
  //   id: 3,
  //   category: ["All", "urban"],
  //   imageUrl: "images/portfolio-item3.jpg",
  //   thumbUrl: "images/portfolio-thumb-3.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 3.",
  // },
  // {
  //   id: 4,
  //   category: ["All", "family", "events"],
  //   imageUrl: "images/portfolio-item4.jpg",
  //   thumbUrl: "images/portfolio-thumb-4.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 4.",
  // },
  // {
  //   id: 5,
  //   category: ["All", "urban"],
  //   imageUrl: "images/portfolio-item5.jpg",
  //   thumbUrl: "images/portfolio-thumb-5.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 5.",
  // },
  // {
  //   id: 6,
  //   category: ["All", "family", "events"],
  //   imageUrl: "images/portfolio-item6.jpg",
  //   thumbUrl: "images/portfolio-thumb-6.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 6.",
  // },
  // {
  //   id: 7,
  //   category: ["All", "urban"],
  //   imageUrl: "images/portfolio-item7.jpg",
  //   thumbUrl: "images/portfolio-thumb-7.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 7.",
  // },
  // {
  //   id: 8,
  //   category: ["All", "family", "events"],
  //   imageUrl: "images/portfolio-item8.jpg",
  //   thumbUrl: "images/portfolio-thumb-8.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 8.",
  // },
  // {
  //   id: 9,
  //   category: ["All", "family"],
  //   imageUrl: "images/portfolio-item001.jpg",
  //   thumbUrl: "images/portfolio-thumb-001.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 9.",
  // },
  // {
  //   id: 10,
  //   category: ["All", "family", "events"],
  //   imageUrl: "images/portfolio-item10.jpg",
  //   thumbUrl: "images/portfolio-thumb-10.jpg",
  //   title: "Sample Caption goes here for Portfolio Item 10.",
  // },
  {
    id: 11,
    category: ["All", "urban"],
    imageUrl: "images/compressjpeg/DSC_8316-min.JPG",
    thumbUrl: "images/compressjpeg/DSC_8316-min.JPG",
    title: "Sample Caption goes here for Portfolio Item 11.",
  },
  {
    id: 13,
    category: ["All", "urban"],
    imageUrl: "images/compressjpeg/DSC_8318-min.JPG",
    thumbUrl: "images/compressjpeg/DSC_8318-min.JPG",
    title: "Sample Caption goes here for Portfolio Item 11.",
  },
  {
    id: 15,
    category: ["All", "urban"],
    imageUrl: "images/compressjpeg/DSC_8323-min.JPG",
    thumbUrl: "images/compressjpeg/DSC_8323-min.JPG",
    title: "Sample Caption goes here for Portfolio Item 11.",
  },
  {
    id: 17,
    category: ["All", "urban"],
    imageUrl: "images/compressjpeg/DSC_8337-min.JPG",
    thumbUrl: "images/compressjpeg/DSC_8337-min.JPG",
    title: "Sample Caption goes here for Portfolio Item 11.",
  },
];
