const imagesData = [
  {
    id: 1,
    category: ["All", "life"],
    imageUrl: "images/Life/DSC_8376.JPG",
    thumbUrl: "images/Life/DSC_8376.JPG",
    title: "Caption1.",
  },
  {
    id: 2,
    category: ["All", "life"],
    imageUrl: "images/Life/car.jpg",
    thumbUrl: "images/Life/car.jpg",
    title: "Caption2.",
  },
  {
    id: 3,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8316.JPG",
    thumbUrl: "images/Family/DSC_8316.JPG",
    title: "Caption3.",
  },
  {
    id: 4,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8319.JPG",
    thumbUrl: "images/Family/DSC_8319.JPG",
    title: "Caption4.",
  },
  {
    id: 5,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8337.JPG",
    thumbUrl: "images/Family/DSC_8337.JPG",
    title: "Caption5.",
  },
  {
    id: 6,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8339.JPG",
    thumbUrl: "images/Family/DSC_8339.JPG",
    title: "Caption5.",
  },
  {
    id: 7,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8348.JPG",
    thumbUrl: "images/Family/DSC_8348.JPG",
    title: "Caption5.",
  },
  {
    id: 8,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8359.JPG",
    thumbUrl: "images/Family/DSC_8359.JPG",
    title: "Caption5.",
  },

  {
    id: 9,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8399.JPG",
    thumbUrl: "images/Family/DSC_8399.JPG",
    title: "Caption9.",
  },
  {
    id: 10,
    category: ["All", "family"],
    imageUrl: "images/Family/DSC_8401.JPG",
    thumbUrl: "images/Family/DSC_8401.JPG",
    title: "Caption9.",
  },
  {
    id: 11,
    category: ["All", "family"],
    imageUrl: "images/Family/family_1.jpg",
    thumbUrl: "images/Family/family_1.jpg",
    title: "Caption9.",
  },
  {
    id: 12,
    category: ["All", "family"],
    imageUrl: "images/Family/family_2.jpg",
    thumbUrl: "images/Family/family_2.jpg",
    title: "Caption9.",
  },
  {
    id: 13,
    category: ["All", "sandalanka_sanda"],
    imageUrl: "images/Sandalanka Sanda/DSC_8391.JPG",
    thumbUrl: "images/Sandalanka Sanda/DSC_8391.JPG",
    title: "Caption10.",
  },
  {
    id: 14,
    category: ["All", "sandalanka_sanda"],
    imageUrl: "images/Sandalanka Sanda/DSC_8394.JPG",
    thumbUrl: "images/Sandalanka Sanda/DSC_8394.JPG",
    title: "Caption11.",
  },
  {
    id: 15,
    category: ["All", "sandalanka_sanda"],
    imageUrl: "images/Sandalanka Sanda/sandalanka_sanda_1.JPG",
    thumbUrl: "images/Sandalanka Sanda/sandalanka_sanda_1.JPG",
    title: "Caption12.",
  },
];
